### ISSUE TITLE
Operaciones basicas-PRÁTICA

### ISSUE THREAD

**Issue by yanet02** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-yanet-02#1]
[OPERACIONES BASICAS....YANET 2 TRABAJO.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-yanet-02/files/7150969/OPERACIONES.BASICAS.YANET.2.TRABAJO.pdf)

**Comment by yaritzaov123** [comment]
20% 
Este trabajo está completo y tiene los  criterios especificados en la rúbrica de evaluación

**Comment by josealfredo79** [comment]
Bien hecho y revisado
